# add an insecure repository
#
#  /etc/docker/daemon.json is used for Docker-CE configuration.
#    see: https://docs.docker.com/registry/insecure/
#  /etc/sysconfig/docker is only effective for CentOS bundled Docker.

- name: read daemon.json file
  command: cat /etc/docker/daemon.json
  register: json
  changed_when: false
  failed_when: false
- set_fact:
    daemon_json: "{{ json.stdout | default('[]', true) | from_json }}"

- name: add an insecure registry 
  set_fact:
    daemon_json: "{{ daemon_json | combine({'insecure-registries' : [ INSECURE_REGISTRY ] }) }}"

- name: write back daemon.json file
  copy:
    content: "{{ daemon_json | to_nice_json }}"
    dest: /etc/docker/daemon.json
  notify: restart docker
