#!/usr/bin/python

import psycopg2
import os
import sys

myhost = os.uname()[1];

dbhost = os.getenv('POSTGRES_SERVICE_SERVICE_HOST')
if dbhost is None:
	dbhost = os.getenv('POSTGRES_PORT_5432_TCP_ADDR')
	if dbhost is None:
		print "<html><head/><body>DB host ENV is not defined.</body></html>"
		sys.exit()

con = psycopg2.connect(host=dbhost, dbname="postgres", user="postgres")

with con:
    print 'Content-type:text/html\r\n\r\n'
    print '<html>'
    print '<head>'
    print '<title>My Application</title>'
    print '</head>'
    print '<body>'
    print 'My host : ' + str(myhost)
    print 'DB : ' + dbhost

    cur = con.cursor()
    cur.execute("INSERT into test (text) VALUES ('" + myhost + "');")
    cur.execute("SELECT id,text,time from test;")

    rows = cur.fetchall()

    for row in rows:
	print '<h2>' + str(row[0]) + ' , ' + str(row[1]) + ' , ' + str(row[2]) + '</h2>'

    print '</body>'
    print '</html>'

