#!/usr/bin/python

import psycopg2
import os
import sys

hostname = os.uname()[1];

dbhost = os.getenv('POSTGRES_SERVICE_HOST')
if dbhost is None:
	dbhost = os.getenv('POSTGRES_PORT_5432_TCP_ADDR')
	if dbhost is None:
    		print 'Content-type:text/html\r\n\r\n'
		print "<html><head/><body>DB host ENV is not defined.</body></html>"
		sys.exit()

con = psycopg2.connect(host=dbhost, dbname="postgres", user="postgres")

with con:
    print 'Content-type:text/html\r\n\r\n'
    print '<html>'
    print '<head>'
    print '<title>Sample Application</title>'
    print '</head>'
    print '<body>'
    print 'hostname: ' + str(hostname)
    print 'dbhost: ' + dbhost

    cur = con.cursor()
    cur.execute("SELECT now();")

    rows = cur.fetchall()

    for row in rows:
	print '<h2> select now(); = ' + str(row[0]) + '</h2>'

    print '</body>'
    print '</html>'

