# using NFS storage as a hostPath volumes in this sample apps
- name: create NFS mount point
  file: path=/mnt/nfs state=directory

- name: mount NFS storage as a shared volume
  mount:
    path: /mnt/nfs
    src: "{{ NFS_SERVER }}:{{ NFS_EXPORT_DIR }}"
    fstype: nfs
    state: mounted
