# Based on the official document:
#  https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

# assumes Flannel as a pod network add-on
- name: initializing master
  command: >
    kubeadm init --pod-network-cidr={{ POD_NETWORK_CIDR }}
    {{ (' --apiserver-advertise-address=' + NODE_IP) if NODE_IP is defined else '' }}
  tags: kubeadm-init

# kubectl configuration - assumes the root user
- name: kube config - create directory
  file:
    path: $HOME/.kube
    state: directory
- name: kube config - copy initial config file
  command: cp /etc/kubernetes/admin.conf $HOME/.kube/config
  args:
    creates: $HOME/.kube/config
#  if you want to run as kubectl as a normal user then need to do below too
#  following to the document.
#    sudo chown $(id -u):$(id -g) $HOME/.kube/config
    

# Install Flannel pod network add-on
#  equivalent to
#    command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml
#  but instead download it once and apply from the local file
#  to allow to customize the iface option to support vagrant environment.
#    https://kubernetes.io/docs/setup/independent/troubleshooting-kubeadm/#default-nic-when-using-flannel-as-the-pod-network-in-vagrant
#
- name: download Flannel pod network add-on
  get_url:
    url: https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml
    dest: /tmp/kube-flannel.yml

- name: customize Flannel iface (if necessary)
  lineinfile:
    path: /tmp/kube-flannel.yml
    insertafter: '- --kube-subnet-mgr'
    line: "        - --iface {{ FLANNELD_IFACE }}"
  when: FLANNELD_IFACE is defined

- name: installing Flannel pod network add-on
  command: kubectl apply -f /tmp/kube-flannel.yml

