- name: download official images into the local insecure registry
  include: download-image.yml
  loop_control:
    loop_var: imagename
  with_items:
    - "postgres:9.6.10"

- name: build apps images
  include_tasks: build-image.yml
  loop_control:
    loop_var: image
  with_items:
    - { tag: "{{ APPS_POSTGRES_IMAGE }}", dir: "db-pod" }
    - { tag: "{{ APPS_HTTPD_IMAGE }}", dir: "web-pod" }

